### ISSUE TITLE
Add support for a secondary dataset for K-Means demos on the Clustering Module

### ISSUE THREAD

**Issue by krisharma** [sandboxnu/a-eye#83] opened 2021-01-27 02:34 UTC
This should be standard over all demos which should be able to access and display that data. 

Ideally, this data should be less separable than the Iris dataset

**Comment by krisharma** [comment] 2021-01-31 21:56
@jakeisnt @dankrasno if GitHub allows it, please link this issue with the PR that resolves this issue. Not sure if it will allow multiple issues to be linked to a single PR.

**Comment by jakeisnt** [comment] 2021-01-31 23:20
@krisharma It's already linked, see #95 as mentioned above

**Comment by jakeisnt** [comment] 2021-02-01 05:18
Ah, that's my bad - the issue is _mentioned_ but not _linked_.

**Comment by jakeisnt** [comment] 2021-02-03 03:02
Closed as the pull request associated with this issue was merged.

**Closed by jakeisnt** 2021-02-03 03:02 UTC
Labels: enhancement
